services:
  relay:
    container_name: gm-relay
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./db:/app/db"
      - "./internal:/app/internal"
    ports:
      - "3336:3336"